### ISSUE TITLE
create form template and controller

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#13]
Create a form for new and changed course proposals. A new proposal should just begin with a blank form, while a changed course proposal should pre-fill the previous data for that course. 

All of the fields we for sure need in the proposals form: course name (i.e. "CS 150"), title, instructor(s), gen. ed. categories it fulfills, credit hours, estimated enrollment, max capacity, term, prerequisites, fees, catalog description, rationale. All fields will be required!

If users can only make proposals in their department, the user won't need to enter a department in the form. We would be able to infer the department. From the department, we can infer the division.

**Comment by mcneky01** [comment]
Does the abbreviation of a course (i.e. CS) match the department that course is in? If so, the user should only need to enter the course number and we can formulate the course name (CS-150) no matter if the department gets entered by the user or inferred from the user.

**Comment by mcneky01** [comment]
Also not sure if we need to require the user to choose the gen ed requirements a class will satisfy. Does every class that exists satisfy at least one gen ed requirement?

**Comment by whatsopdahl** [comment]
Not every class will satisfy a gen-ed requirement. Check database/dbGuide.html for a complete list of gen_ed reqs. Also, to your first question, the abbreviation is mapped to the dept. But, we should have them enter the course name and then infer dept and division from that. We can have some checking in the form to make sure they use a valid dept abbreviation.

**Comment by mcneky01** [comment]
Sounds good for the gen-ed stuff. Shouldn't we just make the department choice a select box since it'll pretty much be a fixed list? That's how I made it for now, and then they could enter a number. We could have the number checked to make sure it's not already used..
