### ISSUE TITLE
New proposal add to recently viewed

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#20]
When trying to add a new proposal or edit an existing proposal, error having to do with adding that proposal to recently viewed:
angular.js:13920 TypeError: Cannot read property 'name' of undefined
    at Object.addToRecentlyViewed (user.js:107)
    at app.js:103

**Comment by whatsopdahl** [comment]
Has been resolved with recent changes. See prod env here

[](http://apc-2017-cs.luther.edu)
