### ISSUE TITLE
old/new descriptions same in proposal

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#23]
Found a proposal that has old and new descriptions as if they are different but they are exactly the same: PSYC-352

**Comment by whatsopdahl** [comment]
Invalid issue: there is a difference in descriptions - additional last line reads "Students conduct original research"

The difference in the pre-req field is due to an extra tab charcter in the old course, hidden from the user as we trim the output.

**Comment by mcneky01** [comment]
Sorry, I was indeed talking about the Pre-Req field. Is this not a valid issue though? I mean I assumed it shows up as different because of a tab or something similar. To us it's fine because we know what's going on but to the user it's an error in our application

**Comment by whatsopdahl** [comment]
I think this is a data issue. if we fix in mock data we should be OK
