### ISSUE TITLE
should new proposal button be somewhere else as well?

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#24]
The new proposal button is only available on the dashboard or my changes pages. it may be nice to include it somewhere else (user menu?) in case someone customizes their preferences to show something besides these two pages

**Comment by whatsopdahl** [comment]
Good idea - but it may be better placed on the navbar to the left of the user menu. just a simple button like this: 

`<button class="btn btn-success"><span class="glyphicon glyphicon-plus"></span></button>`

**Comment by mcneky01** [comment]
We cancelled the user preferences option to choose which page loads per user. The dashboard will be the home page for every user so we don't really need to move this button
