### ISSUE TITLE
Accept and reject buttons

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#25]
Accept and reject buttons should be hidden from everyone once they make it to the registrar's stage. Only the Completed button should show if a user from the registrar's office is logged in. Here are the errors when accept button is clicked when it shouldn't even be available:
(1) angular.js:12011 POST http://localhost:8080/LutherCourseProposal/data 400 ()
(2) angular.js:13920 ERROR :null(anonymous function) @ angular.js:13920handleError @ dataSrv.js:338(anonymous function) @ dataSrv.js:174(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790l @ angular.js:11831J @ angular.js:12033t.onload @ angular.js:11966

**Comment by whatsopdahl** [comment]
Issue has been resolved by adding conditions to the btn-menu.html template
