### ISSUE TITLE
Error when trying to reject proposal

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#26]
(1) angular.js:12011 POST http://localhost:8080/LutherCourseProposal/data 400 ()
(2) angular.js:13920 ERROR :null(anonymous function) @ angular.js:13920handleError @ dataSrv.js:338(anonymous function) @ dataSrv.js:190(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790l @ angular.js:11831J @ angular.js:12033t.onload @ angular.js:11966

**Comment by whatsopdahl** [comment]
Seems it has been resolved by my changes: see prod environment here
[](http://apc-2017-cs.luther.edu)
