### ISSUE TITLE
check if registrar user works correctly once user.role is added to project

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#27]
there are a number of things that should be hidden or shown only if a user from the registrar's office is logged in. once user roles are incorporated into our data model, we should check if those features are working properly

**Comment by whatsopdahl** [comment]
Roles now working. Please verify that all restricted operations are restricted on the front end. 

Current implementation differs than per our earlier discussion -- user.role will be an array of string values
Roles can be:
- Students
- Faculty
- Registrars_Office

Once we get an APC_Developers group, we will sub that one out for Students. That is just temporary so we can play around with it. 

To test this, I recommend commenting out the <Context> tag in the context.xml, adding different users and roles to tomcat.xml and using those roles as tests for the permissions.

**Comment by mcneky01** [comment]
Roles seem to be working on the front end. Hiding or showing the correct buttons and pages seems to be working as planned too
