### ISSUE TITLE
Proposal sort by last name?

### ISSUE THREAD

**Issue by mcneky01** [whatsopdahl/apc_interface#28]
Should proposal sort go by last name instead of first name?

**Comment by whatsopdahl** [comment]
No - Unfortunately, we only store the name as a single string, so implementing a sort on the last name will be too time consuming to undertake at this point.

**Comment by mcneky01** [comment]
This could still be an enhancement for future work study students. It doesn't need to be done right away but I think some users would like to sort by last name.
