### ISSUE TITLE
Revise dashboard.html template

### ISSUE THREAD

**Issue by whatsopdahl** [whatsopdahl/apc_interface#8]
Adjust the sections of the dashboard to fill the page vertically. 
As much as possible, try to use bootstrap built-in classes. Find documentation here: 
[http://getbootstrap.com/css/]

**Comment by mcneky01** [comment]
the sections will fill in nicely when we add html to them. once we start filling in the sections, we may need to tweak the css a bit for cases like no classes showing up in a section or very large sections
